version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: gatepass-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: college_gatepass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  gatepass-app:
    build: .
    container_name: gatepass-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/college_gatepass
      DB_USERNAME: root
      DB_PASSWORD: root
      SERVER_PORT: 8080
    volumes:
      - uploads_data:/app/uploads

volumes:
  mysql_data:
  uploads_data:
